name: Release Portfolio Build

on:
  push:
    branches: [master]

jobs:
  init_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

  build_api_server:
    name: Build Portfolio API Server
    needs: init_repo

    runs-on: ubuntu-latest

    steps:
      - name: Chaning directory
        run: cd ./server

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

  build_ui_application:
    runs-on: ubuntu-latest
    needs: init_repo

    strategy:
      matrix:
        node_version: ["16.x"]

    steps:
      - name: Chaning directory
        run: cd ./app-ui

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Packing build result
        run: |
          cd ./dist
          zip ../app-ui.zip ./* -r

  install_api_server:
    runs-on: ubuntu-latest
    needs: [build_ui_application]

    steps:
      - name: Uploading to production server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          port: 22
          key: ${{ secrets.PRODUCTION_PPK }}
          source: ./server/target/release/portfolio-web-api
          target: ~/install_release/
          overwrite: true

      - name: Unpacking and installing uploaded release
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          port: 22
          key: ${{ secrets.PRODUCTION_PPK }}
          script: ~/start_server.sh

  install_ui_application:
    runs-on: ubuntu-latest
    needs: [build_ui_application]

    steps:
      - name: Uploading To Production Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          port: 22
          key: ${{ secrets.PRODUCTION_PPK }}
          source: ./app-ui/app-ui.zip
          target: ~/
          strip_components: 1
          overwrite: true

      - name: Unpacking and installing uploaded release
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          port: 22
          key: ${{ secrets.PRODUCTION_PPK }}
          script: ~/install_release.sh

  upload_release_artifact:
    runs-on: ubuntu-latest
    needs: [build_api_server, build_ui_application]

    steps:
      - name: Prepearing final release artifact
        run: |
          mkdir ./artifact
          mkdir ./artifact/server
          mkdir ./artifact/app-ui
          cp ./server/target/release/portfolio-web-api ./artifact/server
          cp -a ./app-ui/dist/. ./artifact/app-ui

      - name: Packing final release artifact
        run: |
          cd ./artifact
          zip ../artifact.zip ./* -r

      - name: Project Information
        id: project_info
        uses: gregoranders/nodejs-project-info@v0.0.18

      - name: Creating new release
        id: create_release
        uses: gregoranders/nodejs-create-release@v0.0.18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ steps.project_info.outputs.version }}
          name: Win95 Portfolio - ${{ steps.project_info.outputs.version }} Release
          target: ${{ github.ref }}

      - name: Upload Release Assets
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifact.zip
          asset_name: artifact.zip
          asset_content_type: application/zip
