name: Portfolio API Build

on:
  push:
    branches: [master]

jobs:
  build_and_test:
    name: Build Portfolio API

    runs-on: ubuntu-latest

    steps:
      - name: Chaning directory
        run: cd ./server

      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Uploading to production server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          port: 22
          key: ${{ secrets.PRODUCTION_PPK }}
          source: ./target/release/portfolio-web-api
          target: ~/
          overwrite: true

      - name: Unpacking and installing uploaded release
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          port: 22
          key: ${{ secrets.PRODUCTION_PPK }}
          script: ~/start_server.sh
